### ISSUE TITLE
String with "/" breaks it

### ISSUE THREAD

**Issue by taylorchance** [jlucaspains/sharp-recipe-parser#116]
Its throwing an error for any ingredient that has a / in it. I fixed it on my end like so:

```parseIngredient(props.ingredient.replace('/', 'or'), 'en')```

Should be an easy fix. Keep up the good work!

**Comment by jlucaspains** [comment]
Hey @taylorchance. I think this is happening because the parser uses / to determine whether the value is a fraction. Let me see how the code can be improved to handle this. Do you have an example line where you saw the issue? While it is easy to make it happen on my end, I can add your scenario(s) to unit tests. Cheers!

**Comment by jlucaspains** [comment]
Alright, I got a fix for it. Long story short, instead of relying on the existence of the / to determine the value is a fraction, it now checks for the token immediately before and after the /. The following tests were added:

1. carrot/parsnip: quantity is 0 or nothing
2. 1/parsnip: quantity is 1
3. carrot/1: quantity is 1
4. 1 1/carrot: quantity is 1 (text quantity is 1 1)

Once @taylorchance provide their scenario, I can close the PR and publish a new version.
